# Generated by Django 4.2.6 on 2023-11-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('student_dept', models.CharField(max_length=50)),
                ('student_phn', models.CharField(max_length=15)),
                ('student_age', models.FloatField()),
                ('student_sex', models.CharField(max_length=10)),
            ],
        ),
    ]
