# Generated by Django 4.2.6 on 2023-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataScience_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=12)),
                ('course_name', models.CharField(max_length=30)),
                ('credit', models.IntegerField()),
                ('course_fee', models.IntegerField()),
            ],
        ),
    ]
